### ISSUE TITLE
import maps from magicavoxel?

### ISSUE THREAD

**Issue by vinport16** [vinport16/chunkball#18]
magica voxel is a voxel editor with a very developed UI etc. If we can export files from there to use as maps, it would be nice. but it might be necessary to first import them into the map editor. this is, just something to think about

**Comment by vinport16** [comment]
https://github.com/kevzettler/parse-magica-voxel

**Comment by mes258** [comment]
https://github.com/vinport16/chunkball.github.io/pull/28
